### ISSUE TITLE
480p és SD dupe-ra vonatkozó szabályok.

### ISSUE THREAD

**Issue by pcroland** [encoding-hun/rules-and-standards#13]
`480p` és `SD` release DUPE-olja egymást. Ha már van `SD` encode, az nem cserélhető `480p`-re csak a felbontás miatt, sem fordítva. `PROPER` vagy `READ.NFO` esetén lehet `SD`-t `480p`-vel javítani/upgrade-elni, és fordítva.

Ez így mindenkinek megfelel? Thumbs up/down-al szavazzunk. 👍/👎?

**Comment by l00tzOMG** [comment]
Elfogadva.
